# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1fcb409f5d83def5b640c8369bd24d23"
name = "leon-app"
handle = "leon-app-2"
application_url = "https://remix-mu-ivory.vercel.app"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://remix-mu-ivory.vercel.app/auth/callback",
  "https://remix-mu-ivory.vercel.app/auth/shopify/callback",
  "https://remix-mu-ivory.vercel.app/api/auth/callback"
]

[pos]
embedded = false
