import { loggerService } from '../logger';

/**
 * 密钥管理类
 * 用于生成和管理用于签名和验证token的公钥和私钥
 */
export class KeyManager {
  private static CLASS_NAME = 'KeyManager';

  // 直接在代码中定义一个固定的私钥（仅用于开发环境）
  // 在生产环境中，应该从环境变量或安全的密钥管理系统中获取
  private static privateKey: string = `-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEAuFZQbCw+PwuLJ+Qk5UzrxQqCVVZ8FwlybMLvtbZ+r7MaAFaw
Vf8PxQj5+NQZfgZxCKmZU0vKvL/aYwkJCYLXg+CuiG/s8XK6APIAW0CxuLRAwjEA
xS9HMBpdCQyWXdYZQJXHvh9dIGRXrLbJTF0YQmK1C9uj0DLFt+LpSW2d0xwoFp7c
X0jZVbGnHCY8S2GhPYoQUXBVZBSEe9JOO1gXnRYSWzIqpPZMHnk1xWy7/BtLLcfP
PQK+aFzn9lXB8FzFHUBqLGQOGjJ/FIgCMGH0/NGQYdOylR8n+/+1FlZYBYIiXHVi
sSzk3jlPmwHTeRyEAL/rk8FS0zJYlNKEXB+KQQIDAQABAoIBADGsf8TWtOH9yGoS
ES9hu90ttsbjqAUNhdv+r0O5VHKGUu7PmyKtS5HEPqzOy5eBUCcLgIbFKAdEiVeJ
qURXIHmGGJiDxN+/bpnXjpZrVKA3EnaUFsJkMHsLjM+7ZuDlmzRUwq82DB4NLgJM
Ck9LJzKJNQmEOShh1KPwJQQNvg8YnVXCjeXYsHZ2wfgXcJBIzL3Klk387vrxHUDX
0Sh1iKwBZO9kjUHl5HuG4bokMNjbHvp37J/aUPwl9yrQmyGKNLWI9YRwH8mYmKKW
5B0kR4S4nJKGdxmwQmMrwIXEQgVJJR9gKv5BTOlDVkLfm9yKBZNEwgGKDYG5FHUa
OkRYjAECgYEA3dUg8DXzo4g0fmWNzQWjgZvZIjLjMucKvpYRfCXrGNDKxwgZ6AYO
fHKmHd0qOIUm3o/8KkszOECJbMKSIDtmYgW/wUUEPHbiJc5Z6VQf5/qkjvZ2PWea
OsX9PJRYyf8IJXbszAdpY+SBkxNWHQqvZfEzWdmf7xqXHcXF2ZqEEIECgYEA1Tzm
mjJq7M6f+zMo7DpRwFazGMmrLKFmHiGKFLIcCVwZBQKrVmhP2vat4M6jNgYCJSzv
86F7PfYuiHJRQYzSUDK/YmgGx9wHhDpqjuBASDO2RoK7Dv9SQmYYl415T9on+hTU
tcHzuCNSpJmjQC9mNZxsOKjmvkXf9iyiMZnVGcECgYAJlt9or2BFbfJKYoRFQAVh
I5eyszZYvgcCJ4Vcrb3f3zXGxOUwJEKIqOVZYkzlB8FmGCfWUmEp6AQJRXCvJtLi
5Z1wZLzZTCOPgkEwGv3pWIx/9CZqrLLdLRWVPp8+hfZKxSsImKPdwwJHLMeJw5JH
Hdj0XWw9iDTLQfYkBQJ0gQKBgQCkHkmJucKG/3j2LjZJLI8LYTPUBA4vLNcLRxhG
XssNRRQGGn8hn0TjCrKh0LVs3Izrxv9aS2AvwGnimFzKJzGCX7BQJZM3euc68yiL
oWvvfpG5wLQiCPpejouF6qJBIUlJrQr9zBfQDmJ/Gpbb7RV+3XBsIWlqwVy3JyO6
oPR9wQKBgGqJN4TvIwDmO7U4BoYu0CmJQGNHjFEgHlmsCbX3GGVvkY9upRxEzhP4
IPT6YaYujm3UpKUYCmMwKfL0u0CQQGJQJIzqFZN8Ugwnk7jQvZHde8Cp6Zj4HoIw
YFVKI6QMFyNKvTaZLqPSzGvZJCQVD0Nz1nUxzBXRRx9hLBGJGqFh
-----END RSA PRIVATE KEY-----`;

  // 对应的公钥
  private static publicKey: string = `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuFZQbCw+PwuLJ+Qk5Uzr
xQqCVVZ8FwlybMLvtbZ+r7MaAFawVf8PxQj5+NQZfgZxCKmZU0vKvL/aYwkJCYLX
g+CuiG/s8XK6APIAW0CxuLRAwjEAxS9HMBpdCQyWXdYZQJXHvh9dIGRXrLbJTF0Y
QmK1C9uj0DLFt+LpSW2d0xwoFp7cX0jZVbGnHCY8S2GhPYoQUXBVZBSEe9JOO1gX
nRYSWzIqpPZMHnk1xWy7/BtLLcfPPQK+aFzn9lXB8FzFHUBqLGQOGjJ/FIgCMGH0
/NGQYdOylR8n+/+1FlZYBYIiXHVisSzk3jlPmwHTeRyEAL/rk8FS0zJYlNKEXB+K
QQIDAQAB
-----END PUBLIC KEY-----`;

  /**
   * 获取私钥
   */
  public static getPrivateKey(): string {
    return this.privateKey;
  }

  /**
   * 获取公钥
   */
  public static getPublicKey(): string {
    return this.publicKey;
  }
}
