import { loggerService } from '../logger';

/**
 * 密钥管理类
 * 用于生成和管理用于签名和验证token的公钥和私钥
 */
export class KeyManager {
  private static CLASS_NAME = 'KeyManager';

  // 直接在代码中定义一个固定的私钥（仅用于开发环境）
  // 在生产环境中，应该从环境变量或安全的密钥管理系统中获取
  private static privateKey: string = `-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEAzSwjDn/LTQkfK8F5IuhYyKYiwXN5vaqqKPPYJ1e7ETL4Y1q4
EQbgV+SfvX7VQbpAQAresU5H+7xwQCNucvVPdHpQm+xmTLKePSUUbLTwfOl5HqZG
ELR5gzx5XbJkgJdFjVYQXW1XbqNBG/dw7MMj+tpxJEiBGIL0EUbHcxnKLvgRLJ8b
vxjbIRRVMHDJOYf7bicD9T9SaJ6iYwKhBUjSsT2VEYIADmOTQvpGvXWG/QEqYRQH
XYsL+Pu8lmAj6hFpJpyHL+NwDXJVWuXo6xvJXKH+wqAQUbWl0m+IMPfwzRQGM/cj
X7UX3X5KOHkKToGbcVuwaTgZBjGZ8iBHgQIDAQABAoIBAQCVBxEsKvjVXL0sJgrU
IQNej5Icmmd9wHdjYkqQjCJpKfz+8i8A5/SnVL3CU5yDe7xBKs5R6GGxuPxEGgJh
oVKZZ7FO+FRVpLJGLpjLVkJle8Jf/3tidal0GYyeAM8RZnV+75QKJJt8WGgMvS4U
RwNkj4xQeGGQxGDwOKXVaHgWOYxAK5m9uRNyN7YL8o+0yS7LQUcjnXyUKEHADZJK
HNxvU6UUM4VjCuhQ0WhBmixBX4OMwLIV/G4VBPiLe+49vQWStLEBQYCyles2KPo/
CaZdHMX7lY5TRWzTCHjPKd/BsUhDHc0mSP+ZgGZHe5kPcJTFomYUYSs8cIWQ+K2R
QQVBAoGBAPKyvM3HdwA/0TwODTJKCEmtZ5ACZsmvvHxiV4uy8o6xYjAQNYlwgbPf
N8FzqKlJzUhwYLLYDMZ2UndGj6oaXvYlV9sPRbNF8O48Z8NuZqtZsGNX8PNFTv1E
JbQJTvYiaAf/Uw9jDlLbiN4/PE2Wn5JlKlEA7xwRDEuG598QjDIJAoGBANiOX1+J
8mrqKKGHJ8q3FMeIVpjwpEm5JVNZ/nUjdZnXDo3e7ZjukQfABcFPxbgj0COp+GqQ
JPxRTB7A7R8s8/e7BWtQVYoKfF1k0iVN3qxZY3CyhkZOAUm7mGnNy+LiUCfOjt6c
sBQuE3wMJz3YP8Hp4JxQYdk+DVJvtJZZPJZJAoGAJcUjYvdOJHUeGbDJQYX1vPeM
KHUCpSQpGVUz0bLfRzOqDTPBOa6RRFSJ+ddvW/lIBSR+c7z+oRYQMqQFpkQOUKBw
ByqEPdYfOrQpKUZMmwjYcSgv9LMHAlLnGjgcA8qKZ3xZ9Cd7Zz1bZPHArOTbIYm+
lS/FkBau7xEUHEpW5okCgYEAobYCi98+3GzLvhpbAWGQciQWRbfLFjQGxNLX9vUL
BRMn5Ew4zDmN41SQlF0m5kj2zJ6/HOT7WmZH/4/Tb5yBKNdyIEPm/U0yAoM5dIaL
OrfNYTzGjOiGTN2z+AOdB+Z7JWBM8D+ytS7IqR1YHpVXJ5KBs8qqGgwSQQ4EYYsH
qVkCgYBuTDyY1ZUfYUZQZEILm9FiHZfmY5RnP6YnFqwKmcvAYEnxLwfFBa8nVnuk
MGdUjQ5HCVH7Rb+ZklvkAVaEIRxn8oOkWdLjxmVY4QbvL6iBU4qgOIFZtJVpZrMy
AkwxRdZp1WMnJ+y/fYavHWTsD0/aG1kNzLMxxi3lfQgEPJl/6g==
-----END RSA PRIVATE KEY-----`;

  // 对应的公钥
  private static publicKey: string = `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzSwjDn/LTQkfK8F5IuhY
yKYiwXN5vaqqKPPYJ1e7ETL4Y1q4EQbgV+SfvX7VQbpAQAresU5H+7xwQCNucvVP
dHpQm+xmTLKePSUUbLTwfOl5HqZGELR5gzx5XbJkgJdFjVYQXW1XbqNBG/dw7MMj
+tpxJEiBGIL0EUbHcxnKLvgRLJ8bvxjbIRRVMHDJOYf7bicD9T9SaJ6iYwKhBUjS
sT2VEYIADmOTQvpGvXWG/QEqYRQHXYsL+Pu8lmAj6hFpJpyHL+NwDXJVWuXo6xvJ
XKH+wqAQUbWl0m+IMPfwzRQGM/cjX7UX3X5KOHkKToGbcVuwaTgZBjGZ8iBHgQID
AQAB
-----END PUBLIC KEY-----`;

  /**
   * 获取私钥
   */
  public static getPrivateKey(): string {
    return this.privateKey;
  }

  /**
   * 获取公钥
   */
  public static getPublicKey(): string {
    return this.publicKey;
  }
}
